name: Sync github to AWS S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  tibcert_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# aws-region
          aws-region: us-east-1
      - name: Deploy static site to S3 bucket
      
# Your bucker name
        run: aws s3 sync . s3://timeline-target-attack  --exclude '.git*/*'
